# Generated by Django 5.0.6 on 2024-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Collector", "Collector"),
                    ("Employee", "Employee"),
                ],
                max_length=255,
            ),
        ),
    ]
