# Generated by Django 5.0.6 on 2024-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
